<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="linvm" ignored="0" name="Surefire test" tests="1" failures="1" timestamp="23 Apr 2021 08:13:34 GMT" time="10.458" errors="0">
  <testcase name="TestSystem" time="6.929" classname="io.hetu.core.plugin.cloudface.TestFinal">
    <failure type="java.lang.AssertionError" message="Expected only one result unique result, but got [0, -1] expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: Expected only one result unique result, but got [0, -1] expected [1] but found [2]
	at io.prestosql.operator.scalar.FunctionAssertions.selectUniqueValue(FunctionAssertions.java:308)
	at io.prestosql.operator.scalar.FunctionAssertions.selectSingleValue(FunctionAssertions.java:299)
	at io.prestosql.operator.scalar.FunctionAssertions.assertFunction(FunctionAssertions.java:262)
	at io.prestosql.operator.scalar.AbstractTestFunctions.assertFunction(AbstractTestFunctions.java:92)
	at io.hetu.core.plugin.cloudface.TestFinal.TestSystem(TestFinal.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- TestSystem -->
</testsuite> <!-- Surefire test -->
